[tool.poetry]
name = "questioncount"
version = "0.1.0"
description = ""
authors = ["dhananjay manjare <dhananjay.manjare@docquity.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.1.0"
pika = "^1.3.2"
pymongo = "^4.10.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
